// Deliberately no "import server-only" here (unlike the rest of src/lib) —
// this file is also imported by the plain tsx CLI script
// (src/db/seed-demo.ts), which runs outside Next's bundler where that
// package can't resolve. Both actual callers (the CLI script and the
// server-only API route below) are already server contexts, so the guard
// would be belt-and-suspenders at best.
import { inArray, like } from "drizzle-orm";
import bcrypt from "bcryptjs";
import type { PostgresJsDatabase } from "drizzle-orm/postgres-js";
import * as schema from "@/db/schema";
import { users, brands, brandMembers, battles, votes, comments, likes, follows } from "@/db/schema";

// Demo content seed — makes the feed feel alive with realistic-looking
// brand duels instead of the leftover "Live P7 A" QA rows from manual
// testing. Every row this creates is namespaced so it can be safely re-run
// against any environment (including prod) without ever touching a real
// user or brand:
//   - fictional brand owners + viewers all use @marketmatcher.demo emails
//   - the 16 fictional brand slugs are hardcoded below (no real trademarks —
//     the master prompt explicitly said not to use real brand logos/assets,
//     and using real company names as "losers" in a demo carries the same
//     risk, so these are original names)
// Re-running wipes and recreates only rows tied to those namespaces.
//
// Videos are static files under public/demo/videos/ (generated by
// scripts/generate-demo-videos.sh, already committed) — served by Next.js
// like any other static asset, no Supabase Storage credentials needed.
//
// This is the shared implementation used by both:
//   - src/db/seed-demo.ts (npm run db:seed-demo — a local/CLI connection)
//   - src/app/api/admin/seed-demo/route.ts (a browser-visitable endpoint
//     that runs against whatever DATABASE_URL the deployment already has —
//     so seeding prod never requires a terminal or a copy-pasted connection
//     string).
// Takes a `db` instance rather than opening its own connection, so each
// caller manages its own connection lifecycle.

type Db = PostgresJsDatabase<typeof schema>;

export const DEMO_EMAIL_DOMAIN = "marketmatcher.demo";
export const DEMO_PASSWORD = "Demo1234!"; // shared password for every demo account

const DAY = 24 * 60 * 60 * 1000;
const daysAgo = (n: number) => new Date(Date.now() - n * DAY);
const daysFromNow = (n: number) => new Date(Date.now() + n * DAY);
const videoUrl = (slug: string) => `/demo/videos/${slug}.mp4`;

type BrandSeed = {
  slug: string;
  name: string;
  category: string;
  country: string;
  description: string;
  isGoliath: boolean;
};

const BRANDS: BrandSeed[] = [
  { slug: "kolaris", name: "Kolaris", category: "Food", country: "AT", isGoliath: true, description: "Der Cola-Platzhirsch seit 1962." },
  { slug: "pikola", name: "Pikola", category: "Food", country: "DE", isGoliath: false, description: "Die freche Cola-Alternative aus Berlin." },
  { slug: "velocia", name: "Velocia", category: "Fashion", country: "DE", isGoliath: true, description: "Globale Sportswear-Marke." },
  { slug: "sprintex", name: "Sprintex", category: "Fashion", country: "AT", isGoliath: false, description: "Laufschuh-Startup aus Innsbruck." },
  { slug: "brewhaus", name: "Brewhaus", category: "Food", country: "DE", isGoliath: true, description: "Kaffeerösterei-Kette seit drei Generationen." },
  { slug: "kornerkaffee", name: "Körner Kaffee", category: "Food", country: "AT", isGoliath: false, description: "Dein Kiez-Kaffee aus Wien-Neubau." },
  { slug: "nordwear", name: "Nordwear", category: "Fashion", country: "DE", isGoliath: true, description: "Outdoor-Bekleidung, international." },
  { slug: "stitchlab", name: "Stitchlab", category: "Fashion", country: "AT", isGoliath: false, description: "Nachhaltige Mode, handgenäht in Graz." },
  { slug: "luxora", name: "Luxora", category: "Beauty", country: "CH", isGoliath: true, description: "Premium-Kosmetik seit 1998." },
  { slug: "glowbotanic", name: "Glow Botanic", category: "Beauty", country: "DE", isGoliath: false, description: "Vegane Naturkosmetik aus Leipzig." },
  { slug: "nexucore", name: "Nexucore", category: "Tech", country: "DE", isGoliath: true, description: "Cloud-Infrastruktur für Enterprises." },
  { slug: "byteforge", name: "Byteforge", category: "Tech", country: "AT", isGoliath: false, description: "Dev-Tools-Startup aus Linz." },
  { slug: "autovanta", name: "Autovanta", category: "Automotive", country: "DE", isGoliath: true, description: "Premium-Automobilhersteller." },
  { slug: "voltrix", name: "Voltrix", category: "Automotive", country: "AT", isGoliath: false, description: "E-Mobility-Startup aus Graz." },
  { slug: "pixelrealm", name: "Pixelrealm", category: "Gaming", country: "DE", isGoliath: true, description: "AAA-Spielestudio." },
  { slug: "questforge", name: "Questforge", category: "Gaming", country: "AT", isGoliath: false, description: "Indie-Studio aus Salzburg, 6 Leute." },
];

const VIEWER_COUNT = 150;

type BattleSeed = {
  aSlug: string;
  bSlug: string;
  mode: "scheduled" | "open";
  category: string;
  createdDaysAgo: number;
  stage: "finished" | "live" | "awaiting_both" | "awaiting_one";
  missingSide?: "a" | "b";
  productionDays?: number;
  votingEndsInDays?: number;
  votingEndedDaysAgo?: number;
  totalVotes?: number;
  aShare?: number;
};

const DEFAULT_CATEGORY = "Verkaufe dein Produkt oder deine Leistung in 15 Sekunden";

const BATTLE_SEEDS: BattleSeed[] = [
  { aSlug: "kolaris", bSlug: "pikola", mode: "scheduled", category: DEFAULT_CATEGORY, createdDaysAgo: 25, stage: "finished", votingEndedDaysAgo: 18, totalVotes: 140, aShare: 0.75 },
  { aSlug: "kolaris", bSlug: "pikola", mode: "scheduled", category: "Zeig dein Produkt in einer 15-Sekunden-Werbung", createdDaysAgo: 5, stage: "live", votingEndsInDays: 2, totalVotes: 95, aShare: 0.47 },
  { aSlug: "velocia", bSlug: "sprintex", mode: "scheduled", category: DEFAULT_CATEGORY, createdDaysAgo: 20, stage: "finished", votingEndedDaysAgo: 13, totalVotes: 120, aShare: 0.46 },
  { aSlug: "velocia", bSlug: "sprintex", mode: "scheduled", category: DEFAULT_CATEGORY, createdDaysAgo: 2, stage: "awaiting_both", productionDays: 12 },
  { aSlug: "brewhaus", bSlug: "kornerkaffee", mode: "scheduled", category: DEFAULT_CATEGORY, createdDaysAgo: 15, stage: "finished", votingEndedDaysAgo: 8, totalVotes: 131, aShare: 0.504 },
  { aSlug: "brewhaus", bSlug: "kornerkaffee", mode: "scheduled", category: "Bester Kaffeespruch in 15 Sekunden", createdDaysAgo: 3, stage: "awaiting_one", missingSide: "a", productionDays: 6 },
  { aSlug: "nordwear", bSlug: "stitchlab", mode: "scheduled", category: DEFAULT_CATEGORY, createdDaysAgo: 30, stage: "finished", votingEndedDaysAgo: 23, totalVotes: 110, aShare: 0.88 },
  { aSlug: "nordwear", bSlug: "stitchlab", mode: "scheduled", category: DEFAULT_CATEGORY, createdDaysAgo: 3, stage: "live", votingEndsInDays: 4, totalVotes: 90, aShare: 0.55 },
  { aSlug: "luxora", bSlug: "glowbotanic", mode: "scheduled", category: DEFAULT_CATEGORY, createdDaysAgo: 22, stage: "finished", votingEndedDaysAgo: 15, totalVotes: 125, aShare: 0.39 },
  { aSlug: "luxora", bSlug: "glowbotanic", mode: "scheduled", category: DEFAULT_CATEGORY, createdDaysAgo: 6, stage: "live", votingEndsInDays: 1, totalVotes: 100, aShare: 0.51 },
  { aSlug: "nexucore", bSlug: "byteforge", mode: "scheduled", category: DEFAULT_CATEGORY, createdDaysAgo: 18, stage: "finished", votingEndedDaysAgo: 11, totalVotes: 115, aShare: 0.58 },
  { aSlug: "nexucore", bSlug: "byteforge", mode: "scheduled", category: DEFAULT_CATEGORY, createdDaysAgo: 1, stage: "awaiting_both", productionDays: 13 },
  { aSlug: "autovanta", bSlug: "voltrix", mode: "scheduled", category: DEFAULT_CATEGORY, createdDaysAgo: 17, stage: "finished", votingEndedDaysAgo: 10, totalVotes: 140, aShare: 0.487 },
  { aSlug: "autovanta", bSlug: "voltrix", mode: "scheduled", category: DEFAULT_CATEGORY, createdDaysAgo: 4, stage: "live", votingEndsInDays: 3, totalVotes: 90, aShare: 0.82 },
  { aSlug: "pixelrealm", bSlug: "questforge", mode: "scheduled", category: DEFAULT_CATEGORY, createdDaysAgo: 14, stage: "finished", votingEndedDaysAgo: 7, totalVotes: 100, aShare: 0.55 },
  { aSlug: "pixelrealm", bSlug: "questforge", mode: "scheduled", category: DEFAULT_CATEGORY, createdDaysAgo: 2, stage: "live", votingEndsInDays: 5, totalVotes: 70, aShare: 0.53 },
  { aSlug: "brewhaus", bSlug: "sprintex", mode: "open", category: DEFAULT_CATEGORY, createdDaysAgo: 9, stage: "finished", votingEndedDaysAgo: 2, totalVotes: 55, aShare: 0.47 },
  { aSlug: "nordwear", bSlug: "byteforge", mode: "open", category: DEFAULT_CATEGORY, createdDaysAgo: 1, stage: "live", votingEndsInDays: 6, totalVotes: 15, aShare: 0.47 },
];

const COMMENT_POOL = [
  "Krass, das hätte ich nicht erwartet 👀",
  "Team Underdog hier 🔥",
  "Ehrlich, beide stark – aber knapp für mich.",
  "Das war eine klare Ansage.",
  "Wer hat den Konter gemacht? Genialer Move.",
  "Endlich mal kreative Werbung statt langweiliger Ads.",
  "Das teile ich sofort in unsere Gruppe.",
  "Overrated, aber ok.",
  "Der Champion verdient den Sieg.",
  "David gegen Goliath at its finest.",
  "Beide Seiten haben sich richtig Mühe gegeben.",
  "Das Ende hat mich überrascht.",
];

function pickRandom<T>(pool: T[], n: number): T[] {
  const copy = [...pool];
  const out: T[] = [];
  for (let i = 0; i < n && copy.length > 0; i++) {
    const idx = Math.floor(Math.random() * copy.length);
    out.push(copy.splice(idx, 1)[0]);
  }
  return out;
}

export type SeedDemoResult = { brands: number; battles: number; viewers: number };

export async function seedDemoContent(db: Db): Promise<SeedDemoResult> {
  // Wipe previous demo data first — namespaced, so this only ever touches
  // rows this same function created.
  const slugs = BRANDS.map((b) => b.slug);
  await db.delete(brands).where(inArray(brands.slug, slugs)); // cascades battles/votes/comments/likes/challenges
  await db.delete(users).where(like(users.email, `%@${DEMO_EMAIL_DOMAIN}`)); // cascades brandMembers/follows/etc left over

  const passwordHash = await bcrypt.hash(DEMO_PASSWORD, 12);

  const viewerRows = await db
    .insert(users)
    .values(
      Array.from({ length: VIEWER_COUNT }, (_, i) => ({
        email: `demo-viewer-${i + 1}@${DEMO_EMAIL_DOMAIN}`,
        passwordHash,
        name: `Demo Viewer ${i + 1}`,
        accountType: "assent" as const,
        emailVerifiedAt: new Date(),
      })),
    )
    .returning({ id: users.id });
  const viewerIds = viewerRows.map((r) => r.id);

  const brandIdBySlug = new Map<string, string>();
  for (const b of BRANDS) {
    const [owner] = await db
      .insert(users)
      .values({
        email: `demo-owner-${b.slug}@${DEMO_EMAIL_DOMAIN}`,
        passwordHash,
        name: `${b.name} Team`,
        accountType: "acro",
        emailVerifiedAt: new Date(),
      })
      .returning({ id: users.id });

    const [brand] = await db
      .insert(brands)
      .values({
        name: b.name,
        slug: b.slug,
        description: b.description,
        website: `https://${b.slug}.example`,
        category: b.category,
        country: b.country,
        videoUrl: videoUrl(b.slug),
        videoUploadedAt: daysAgo(40),
      })
      .returning({ id: brands.id });

    await db.insert(brandMembers).values({ brandId: brand.id, userId: owner.id, role: "owner" });
    brandIdBySlug.set(b.slug, brand.id);

    const upsetWinners = new Set(["sprintex", "voltrix", "glowbotanic"]);
    const followerCount = b.isGoliath ? 25 + Math.floor(Math.random() * 20) : upsetWinners.has(b.slug) ? 10 + Math.floor(Math.random() * 8) : 4 + Math.floor(Math.random() * 6);
    const followers = pickRandom(viewerIds, followerCount);
    if (followers.length > 0) {
      await db.insert(follows).values(followers.map((userId) => ({ userId, brandId: brand.id })));
    }
  }

  for (const seed of BATTLE_SEEDS) {
    const brandAId = brandIdBySlug.get(seed.aSlug)!;
    const brandBId = brandIdBySlug.get(seed.bSlug)!;

    const hasVideoA = seed.stage === "finished" || seed.stage === "live" || (seed.stage === "awaiting_one" && seed.missingSide !== "a");
    const hasVideoB = seed.stage === "finished" || seed.stage === "live" || (seed.stage === "awaiting_one" && seed.missingSide !== "b");

    const productionDeadline =
      seed.stage === "awaiting_both" || seed.stage === "awaiting_one" ? daysFromNow(seed.productionDays ?? 10) : null;
    const votingEndsAt =
      seed.stage === "finished"
        ? daysAgo(seed.votingEndedDaysAgo ?? 5)
        : seed.stage === "live"
          ? daysFromNow(seed.votingEndsInDays ?? 3)
          : null;

    const [battle] = await db
      .insert(battles)
      .values({
        brandAId,
        brandBId,
        mode: seed.mode,
        category: seed.category,
        brandAVideoUrl: hasVideoA ? videoUrl(seed.aSlug) : null,
        brandBVideoUrl: hasVideoB ? videoUrl(seed.bSlug) : null,
        brandASubmittedAt: hasVideoA ? daysAgo(seed.createdDaysAgo) : null,
        brandBSubmittedAt: hasVideoB ? daysAgo(seed.createdDaysAgo) : null,
        productionDeadline,
        votingEndsAt,
        createdAt: daysAgo(seed.createdDaysAgo),
      })
      .returning({ id: battles.id });

    if (!seed.totalVotes) continue;

    const total = seed.totalVotes;
    const aVotes = Math.round(total * (seed.aShare ?? 0.5));
    const bVotes = total - aVotes;
    const voters = pickRandom(viewerIds, total);
    const aVoters = voters.slice(0, aVotes);
    const bVoters = voters.slice(aVotes);

    if (aVoters.length > 0) {
      await db.insert(votes).values(aVoters.map((userId) => ({ battleId: battle.id, userId, votedForBrandId: brandAId })));
    }
    if (bVoters.length > 0) {
      await db.insert(votes).values(bVoters.map((userId) => ({ battleId: battle.id, userId, votedForBrandId: brandBId })));
    }

    const aLikers = pickRandom(viewerIds, Math.round(aVotes * 0.6));
    const bLikers = pickRandom(viewerIds, Math.round(bVotes * 0.6));
    if (aLikers.length > 0) await db.insert(likes).values(aLikers.map((userId) => ({ battleId: battle.id, brandId: brandAId, userId })));
    if (bLikers.length > 0) await db.insert(likes).values(bLikers.map((userId) => ({ battleId: battle.id, brandId: brandBId, userId })));

    const commenters = pickRandom(viewerIds, 2 + Math.floor(Math.random() * 4));
    const commentTexts = pickRandom(COMMENT_POOL, commenters.length);
    if (commenters.length > 0) {
      await db.insert(comments).values(
        commenters.map((userId, i) => ({
          battleId: battle.id,
          userId,
          content: commentTexts[i],
          createdAt: daysAgo(Math.random() * (seed.createdDaysAgo / 2)),
        })),
      );
    }
  }

  return { brands: BRANDS.length, battles: BATTLE_SEEDS.length, viewers: VIEWER_COUNT };
}
